"""Question/forecast task data model."""

from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field, ConfigDict, field_validator
from ...core.database import register_model
from .domain import Domain


class QuestionType(str, Enum):
    """Types of forecast questions."""

    BINARY = "binary"  # Two-outcome questions (Yes/No, Up/Down, Win/Lose)
    MCQ = "mcq"  # Multiple choice (3+ outcomes)
    QUANTITY = "quantity"  # Numeric predictions
    TIMEFRAME = "timeframe"  # Date/time predictions


@register_model("questions", indexes=["domain", "difficulty", "source"])
class Question(BaseModel):
    """Benchmark forecast question.

    Questions define the forecasting tasks that LLMs will attempt.
    They include the question text, ground truth answer, and metadata
    about difficulty and temporal constraints.
    """

    # Core identification
    id: str = Field(..., description="Unique question identifier")
    question_text: str = Field(
        ..., min_length=20, description="The forecasting question"
    )
    question_type: QuestionType = Field(..., description="Type of answer expected")

    # Classification
    domain: Domain = Field(..., description="Primary domain")
    source: str = Field(
        ...,
        description="Source system that generated this question (e.g., 'polymarket', 'news', 'synthetic')",
    )
    difficulty: int = Field(..., ge=1, le=5, description="Difficulty rating 1-5")

    # Temporal boundaries
    resolution_date: datetime = Field(
        ..., description="When ground truth becomes available/verifiable"
    )
    estimated_start_time: Optional[datetime] = Field(
        None,
        description=(
            "Recommended starting point when the question becomes valid for forecasting. "
            "Represents when sufficient context is available for informed predictions. "
            "Generated by LLM or fetched from market data."
        ),
    )

    # Ground truth (hidden from forecasters during evaluation)
    ground_truth: Optional[Any] = Field(
        None,
        description="Actual outcome (type depends on question_type). None for unresolved questions.",
    )
    ground_truth_hash: Optional[str] = Field(
        None, description="Cryptographic hash for integrity verification"
    )

    # Event reference (optional - for structured benchmark questions)
    target_event_id: Optional[str] = Field(
        None,
        description="DEPRECATED: Use outcome_event_ids + is_actual_outcome instead. Query Event(is_actual_outcome=True, extracted_for_question_id=question_id) to get actual outcome.",
    )
    outcome_event_ids: List[str] = Field(
        default_factory=list,
        description="IDs of outcome events (Events with is_outcome=True) for this question",
    )
    related_event_ids: List[str] = Field(
        default_factory=list,
        description="Other relevant events (for multi-event or exploratory questions)",
    )
    related_article_ids: List[str] = Field(
        default_factory=list,
        description="Article IDs that this question was generated from",
    )

    # Question-specific metadata
    context: Optional[str] = Field(
        None, description="Background information provided to forecaster"
    )
    resolution_criteria: Optional[str] = Field(
        None,
        description="Objective rules for how to verify/resolve this question (e.g., 'Based on CoinMarketCap closing price on Dec 31, 2024')",
    )
    resolution_reasoning: Optional[str] = Field(
        None,
        description="Evidence and explanation for why the ground_truth is what it is (only for resolved questions)",
    )
    options: Optional[List[str]] = Field(None, description="Options for MCQ questions")
    quantity_unit: Optional[str] = Field(
        None, description="Unit for quantity questions (e.g., 'USD', 'people', 'GW')"
    )
    quantity_bounds: Optional[Dict[str, float]] = Field(
        None, description="Valid range for quantity questions {'min': x, 'max': y}"
    )

    # Graph Building & NL Explanation
    causal_explanation: Optional[str] = Field(
        None,
        description=(
            "NL causal explanation produced by HindsightAgent. "
            "Includes dated events, causal relationships, and article citations [art_id]. "
            "Input to GraphBuilderAgent."
        ),
    )
    graph_built: bool = Field(
        default=False,
        description="Set to True by GraphBuilderAgent after successfully building the causal graph.",
    )
    graph_build_error: Optional[str] = Field(
        None,
        description="Error message if graph building failed.",
    )

    # Metadata
    is_synthetic: bool = Field(
        default=False, description="Whether question uses synthetic data"
    )
    quality_score: Optional[float] = Field(
        None,
        ge=0.0,
        le=1.0,
        description="Composite quality score (0.0-1.0), null if not scored",
    )
    quality_dimensions: Optional[Dict[str, float]] = Field(
        None, description="Detailed scores for each quality dimension"
    )
    skip_evidence: bool = Field(
        default=False,
        description="If True, skip this question in evidence processing (low quality, noisy, etc.)",
    )
    skip_reason: Optional[str] = Field(
        None,
        description="Reason why this question is marked to skip evidence processing",
    )
    quality_warning: Optional[str] = Field(
        None,
        description="Warning about borderline quality issues (still processed, but flagged)",
    )
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    updated_at: Optional[datetime] = Field(None, description="Last update timestamp")

    # Source-specific metadata (stores extra fields from various question sources)
    metadata: Optional[Dict[str, Any]] = Field(
        None,
        description="Additional metadata from question source (market_id, clob_token_ids, etc.)",
    )

    model_config = ConfigDict(
        extra="allow",  # Allow transient fields like cutoff_date during evaluation
        json_schema_extra={
            "example": {
                "id": "q_pol_2024_001",
                "question_text": "Will the Republican candidate win the 2024 US Presidential Election?",
                "question_type": "binary",
                "domain": "politics",
                "difficulty": 4,
                "resolution_date": "2024-11-06T00:00:00Z",
                "ground_truth": True,
                "ground_truth_hash": "sha256:abc123...",
                "target_event_id": "evt_pol_20241105_001",
                "context": "The 2024 United States presidential election will be held on November 5, 2024.",
            }
        },
    )

    @field_validator("question_type", mode="before")
    @classmethod
    def normalize_question_type(cls, v):
        """Normalize legacy 'boolean' question type to 'binary' for backwards compatibility."""
        if v == "boolean":
            return "binary"
        return v

    @field_validator("estimated_start_time")
    @classmethod
    def validate_start_before_resolution(cls, v, info):
        """Ensure estimated_start_time is before resolution_date."""
        if v is not None and "resolution_date" in info.data:
            resolution_date = info.data["resolution_date"]
            if v >= resolution_date:
                raise ValueError(
                    f"estimated_start_time ({v}) must be before resolution_date ({resolution_date})"
                )
        return v

    def validate_prediction(self, prediction: Any) -> bool:
        """Validate that a prediction matches the expected type for this question.

        Args:
            prediction: The prediction to validate

        Returns:
            True if valid, False otherwise
        """
        if self.question_type == QuestionType.BINARY:
            if self.options and len(self.options) == 2:
                normalized_options = {
                    str(option).strip().lower() for option in self.options
                }
                if normalized_options not in (
                    {"yes", "no"},
                    {"true", "false"},
                    {"1", "0"},
                ):
                    return prediction in self.options
            return isinstance(prediction, bool)
        elif self.question_type == QuestionType.MCQ:
            if self.options:
                return prediction in self.options
            return isinstance(prediction, str)
        elif self.question_type == QuestionType.QUANTITY:
            if isinstance(prediction, dict):
                return "lower" in prediction and "upper" in prediction
            return isinstance(prediction, (int, float))
        elif self.question_type == QuestionType.TIMEFRAME:
            # Could be string (ISO datetime) or dict with range
            return isinstance(prediction, (str, dict))
        return False

    def set_evaluation_cutoff(self, cutoff_date: datetime) -> "Question":
        """Set the cutoff date for evaluation/benchmarking (transient, not persisted).

        The cutoff_date simulates the "current time" when a forecaster makes their prediction.
        This is a RUNTIME-ONLY attribute used by the temporal gateway during evaluation.
        It is NOT persisted to the database - it should be set fresh for each evaluation run.

        This should be set during evaluation to ensure fair testing:
        - For resolved events: Set to before the event occurred (to test forecasting ability)
        - For future events: Set to the evaluation time (what info is available now)

        Args:
            cutoff_date: The information cutoff datetime (timezone-aware)

        Returns:
            Self for method chaining

        Example:
            >>> question.set_evaluation_cutoff(datetime(2024, 11, 1, tzinfo=timezone.utc))
        """
        self.cutoff_date = cutoff_date
        return self

    def get_forecast_context_window(self):
        """Get the valid temporal window for forecasting this question.

        Returns ``(window_start, window_end)`` derived from ``estimated_start_time``
        and ``resolution_date``.  Falls back to 30 days before resolution when
        ``estimated_start_time`` is not set.

        Returns:
            (window_start, window_end) datetime tuple

        Example:
            >>> start, end = question.get_forecast_context_window()
        """
        from .question_helpers import calculate_forecast_context_window

        return calculate_forecast_context_window(self)

    def validate_simulated_date(
        self, simulated_date: datetime, window_start: datetime, window_end: datetime
    ):
        """Check if a simulated date is valid for forecasting this question.

        Note: Use prepare_forecast() for the complete workflow. This is a lightweight helper.

        Args:
            simulated_date: The proposed simulation date
            window_start: Start of valid forecast window
            window_end: End of valid forecast window

        Returns:
            (is_valid, error_message) tuple

        Example:
            >>> window_start, window_end = question.get_forecast_context_window()
            >>> valid, error = question.validate_simulated_date(datetime(2025, 11, 3), window_start, window_end)
            >>> if not valid:
            >>>     raise ValueError(error)
        """
        from .question_helpers import validate_simulated_date

        return validate_simulated_date(self, simulated_date, window_start, window_end)

    def suggest_simulated_date(
        self,
        window_start: datetime,
        window_end: datetime,
        offset_days_before_resolution: int = 7,
    ):
        """Get a suggested simulated date for forecasting this question.

        Note: Use prepare_forecast() for the complete workflow. This is a lightweight helper.

        Args:
            window_start: Start of valid forecast window
            window_end: End of valid forecast window
            offset_days_before_resolution: How many days before resolution to suggest

        Returns:
            Suggested datetime for simulation

        Example:
            >>> window_start, window_end = question.get_forecast_context_window()
            >>> simulated_date = question.suggest_simulated_date(window_start, window_end, offset_days_before_resolution=14)
        """
        from .question_helpers import suggest_simulated_date

        return suggest_simulated_date(
            self, window_start, window_end, offset_days_before_resolution
        )

    def prepare_forecast(
        self,
        db=None,
        offset_days_before_resolution: int = 0,
        min_context_items: int = 3,
    ):
        """Get all information needed to forecast this question (hides complexity).

        This single method handles all the setup in one pass:
        - Calculates valid forecast window
        - Suggests appropriate simulated date
        - Validates the setup
        - Returns everything needed

        No redundant calculations - everything happens in a single pass.

        Args:
            db: Database instance for fetching context
            offset_days_before_resolution: How many days before resolution to simulate (default: 0)
            min_context_items: Minimum number of context items needed (default: 3)

        Returns:
            dict with keys:
                - window_start: When forecasting window opens
                - window_end: When forecasting window closes
                - simulated_date: Suggested date to use for forecast
                - days_available: Number of days in forecast window

        Raises:
            ValueError: If insufficient context or invalid configuration

        Example:
            >>> setup = question.prepare_forecast(db, offset_days_before_resolution=7)
            >>> agent = ForecastAgent(question, simulated_date=setup['simulated_date'])
        """
        from .question_helpers import prepare_forecast_context

        return prepare_forecast_context(
            self, db, offset_days_before_resolution, min_context_items
        )
